### ISSUE TITLE
pythonmod: can't parse

### ISSUE THREAD

**Issue by w0ngjowo** [cbuijs/unbound-dns-firewall#27]
hello,
Mar 25 21:09:02 unbound[15271:0] error: pythonmod: can't parse Python script /etc/unbound/dns-firewall.py
Mar 25 21:09:02 unbound[15271:0] error: module init for module python failed
Mar 25 21:09:02 unbound[15271:0] fatal error: failed to setup modules

I tried to install but get an error like this, guess what is wrong?
please help

**Comment by cbuijs** [comment]
Hi @w0ngjowo ,

Hard to tell. Can you start unbound in the foreground and provide what is shown on the screen?

Use `-d` to start unbound in foreground, example: `unbound -d -c /etc/unbound/unbound.conf`

My guess would be you are missing some python modules (check the `import` lines in `dns-firewall.py`).

Also, you need to run Python **2.6** or newer but **NOT** python 3.

Modules you need to install using `pip install` as they are not default:
```
thread
requests
regex
pytricia
expiringdict
python-unbound
```
Also make sure the `sys.path.append` line has the right path of `dist-packages` for your system/os/python setup.

Also make sure you have the unbound python module installed, on Debian (which I use), you need to install an extra package called `python-unbound` for example.

Also unbound needs to be compiled with python support (use `configure` parameter `--with-pythonmodule`).

Hope this helps, let me know if you got it working or need more assistance, happy to help.

**Comment by w0ngjowo** [comment]
here log

unbound -d -c /etc/unbound/unbound.conf
Traceback (most recent call last):
  File "/etc/unbound/dns-firewall.py", line 69, in <module>
    import os, os.path, commands, datetime, gc
ImportError: No module named 'commands'

ns-filter:/etc/unbound# python -V
Python 2.7.13
ns-filter:/etc/unbound#

----------------
i already install 
requests
regex
pytricia
expiringdict
python-unbound

and sys.path.append to /usr/lib/python2.7/dist-packages/

Thx u

**Comment by cbuijs** [comment]
@w0ngjowo 

So it seems "commands" is missing or cannot be found. Looks like you are using Python3 instead of Python2 as Python3 discontinued `commands`. Run `env python` from the prompt and see what is started.

Can you run python from the prompt and enter `import commands` and see what comes back?
```
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import commands
>>>
```
It should return with nothing (as above) and come back to the prompt without errors.

You might want to make sure you are using python 2.7 by changing the shebang in the top of `dns-firewall.py` and "hard-code" it in.

Change:
`#!/usr/bin/env python`
into:
`#!/usr/bin/python`
(The python 2.x executable)

How command `env python` should execute as example:
```
# env python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by cbuijs** [comment]
@w0ngjowo 

Remembering something...

Are you running unbound in chroot mode? That is not supported anyway (python-unbound is flackey running chroot), remove all chroot stuff from unbound.conf.

**Comment by w0ngjowo** [comment]
this fresh debian 9.3 server. i only install trough apt-get, and not run on chroot

Change:
#!/usr/bin/env python
into:
#!/usr/bin/python
(The python 2.x executable)

still same error.

here log

ns-filter:/etc/unbound# env python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import commands
>>>

if sys.path.append set to /usr/lib/python2.7/ 

ns-filter:/etc/unbound# unbound -d -c /etc/unbound/unbound.conf
Mar 25 23:45:51 unbound[23273:0] warning: did not exit gracefully last time (23236)
Traceback (most recent call last):
  File "/etc/unbound/dns-firewall.py", line 69, in <module>
    import os, os.path, commands, datetime, gc
  File "/usr/lib/python2.7/commands.py", line 21, in <module>
    from warnings import warnpy3k
ImportError: cannot import name 'warnpy3k'

sorry for my bad english

**Comment by cbuijs** [comment]
@w0ngjowo 

No, not chroot environment, unbound has the capability to chroot on its own.

Check `/etc/unbound/unbound.conf` and make sure the chroot line is like this:

`chroot: ""`

(two double-quotes as value).

In Debian, Unbound is configured to switch to chroot when configured and it is by default when no chroot is configured, you NEED above line in your `unbound.conf` to make the python module work.

No worries about the English, you are doing fine ;-).

**Comment by w0ngjowo** [comment]
here my unbound.conf

server:
    verbosity: 1

    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    access-control: 0.0.0.0/0 refuse
    access-control: 127.0.0.0/8 allow
    access-control: xxx.xxx.xxx.0/22 allow

#    root-hints: "/etc/unbound/root.hints"
    hide-identity: yes
    hide-version: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: yes
    cache-min-ttl: 300
    cache-max-ttl: 1800
    prefetch: yes
    num-threads: 4

    msg-cache-slabs: 8
    rrset-cache-slabs: 8
    infra-cache-slabs: 8
    key-cache-slabs: 8

    rrset-cache-size: 256m
    msg-cache-size: 128m

### LOGGING ###
        logfile: /var/log/unbound/unbound.log
        use-syslog: no
        log-time-ascii: yes
        log-queries: yes
        val-log-level: 2
server:
    chroot: ""
    module-config: "python validator iterator"
python:
    python-script: "/etc/unbound/dns-firewall.py"

include: "/etc/unbound/unbound.conf.d/*.conf"

-----------------------------------------------------
still same error

**Comment by cbuijs** [comment]
@w0ngjowo 

Can you do this (just to evaluate things):

Change the line:
`python-script: "/etc/unbound/dns-firewall.py"`
to:
`python-script: "/etc/unbound/dns-firewall.pyc"`
(change extension .py to .pyc)

Then do the following:
- `cd /etc/unbound`
- `python -m compileall dns-firewall.py`

Then start unbound again and post the output from all of above.

**Comment by w0ngjowo** [comment]
@cbuijs 

here the log

ns-filter:/etc/unbound# python -m compileall dns-firewall.py
Compiling dns-firewall.py ...
ns-filter:/etc/unbound# 

ns-filter:/etc/unbound# unbound -d -c /etc/unbound/unbound.conf
Mar 26 00:18:02 unbound[19506:0] warning: did not exit gracefully last time (19467)
RuntimeError: Bad magic number in .pyc file
ns-filter:/etc/unbound#

**Comment by cbuijs** [comment]
@w0ngjowo 

Just thinking... Not sure why "commands" is still in there, should run fine without. I think I used it in older versions for something.

Can you change line:
`import os, os.path, commands, datetime, gc`
to:
`import os, os.path, datetime, gc`
(removing commands)

... and restart unbound?

**Comment by w0ngjowo** [comment]
@cbuijs 
here
ns-filter:/etc/unbound# unbound -d -c /etc/unbound/unbound.conf
Mar 26 00:32:09 unbound[19672:0] warning: did not exit gracefully last time (19660)
Traceback (most recent call last):
  File "/etc/unbound/dns-firewall.py", line 70, in <module>
    from thread import start_new_thread
ImportError: No module named 'thread'

ns-filter:/etc/unbound# pip install thread
Collecting thread
  Could not find a version that satisfies the requirement thread (from versions: )
No matching distribution found for thread
ns-filter:/etc/unbound#

**Comment by w0ngjowo** [comment]
its like debian server use python3 library

**Comment by cbuijs** [comment]
@w0ngjowo 

I still think you kind of using python3 somehow.

Can you change:
`from thread import start_new_thread`
to
`from _thread import start_new_thread`
(add underscore to `thread`)

If this works you are using python3 instead of 2. You might want to do `apt-get install python3-unbound` but probably breaks more and I did not test it (on my to-do list).

**Comment by w0ngjowo** [comment]
@cbuijs 

unbound -d -c /etc/unbound/unbound.conf
Mar 26 00:45:48 unbound[19770:0] warning: did not exit gracefully last time (19756)
Traceback (most recent call last):
  File "/etc/unbound/dns-firewall.py", line 82, in <module>
    import regex
  File "/usr/lib/python3/dist-packages/regex.py", line 491
    except error, e:
                ^
SyntaxError: invalid syntax

**Comment by cbuijs** [comment]
@w0ngjowo 

AH! Python-**3** ...

You might want to uninstall `python3-unbound` with `apt` and (re)install `python-unbound`.
```
apt-get remove --purge python3-unbound
apt-get install python-unbound
```
You **CANNOT** have both installed at the same time.

**Comment by w0ngjowo** [comment]
@cbuijs 
 i change module-config: "python validator iterator" to module-config: "python2.7 validator iterator" and its work,
root@ns-filter:/etc/unbound# unbound -d -c /etc/unbound/unbound.conf
Mar 26 01:13:37 unbound[20786:0] warning: did not exit gracefully last time (20766)
root@ns-filter:/etc/unbound#

but if i start server its cannot run,

root@ns-filter:/etc/unbound# service unbound start
root@ns-filter:/etc/unbound# service unbound status
● unbound.service - Unbound DNS server
   Loaded: loaded (/lib/systemd/system/unbound.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-03-26 01:14:23 WIB; 1s ago
     Docs: man:unbound(8)
  Process: 20876 ExecStart=/usr/sbin/unbound -d $DAEMON_OPTS (code=exited, status=1/FAILURE)
  Process: 20870 ExecStartPre=/usr/lib/unbound/package-helper root_trust_anchor_update (code=exited, status=0/SUCCESS)
  Process: 20866 ExecStartPre=/usr/lib/unbound/package-helper chroot_setup (code=exited, status=0/SUCCESS)
 Main PID: 20876 (code=exited, status=1/FAILURE)

Mar 26 01:14:23 ns-filter systemd[1]: unbound.service: Failed with result 'exit-code'.
Mar 26 01:14:23 ns-filter systemd[1]: unbound.service: Service hold-off time over, scheduling restart.
Mar 26 01:14:23 ns-filter systemd[1]: Stopped Unbound DNS server.
Mar 26 01:14:23 ns-filter systemd[1]: unbound.service: Start request repeated too quickly.
Mar 26 01:14:23 ns-filter systemd[1]: Failed to start Unbound DNS server.
Mar 26 01:14:23 ns-filter systemd[1]: unbound.service: Unit entered failed state.
Mar 26 01:14:23 ns-filter systemd[1]: unbound.service: Failed with result 'exit-code'.
root@ns-filter:/etc/unbound#

**Comment by cbuijs** [comment]
@w0ngjowo 

The `module-config` directive does not support `python2.7` as value, it has to be `python`. Nothing to do with the python executable.

So your server is existing due to an config error:

`error: Unknown value for next module: '2.7 iterator'`

When running unbound in foreground (with `-d`), it should not "exit" until you press ctrl-c.

The problem is your python setup and how unbound uses it.

My setup:

- Freshly installed Debian 9.4 (latest)
- `apt-get update && apt-get -y dist-upgrade`
- `reboot`
- `apt-get install unbound unbound-anchor unbound-host python-unbound`
- `pip install --upgrade requests regex pytricia expiringdict`

**Comment by w0ngjowo** [comment]
@cbuijs 
strange,

root@ns-filter:/etc/unbound# unbound -d -c unbound.conf
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'unboundmodule'
root@ns-filter:/etc/unbound# history
    1  nano /etc/apt/sources.list
    2  apt-get update && apt-get -y dist-upgrade && reboot
    3  nano /etc/apt/sources.list
    4  apt-get update && apt-get -y dist-upgrade
    5  apt-get install unbound unbound-anchor unbound-host python-unbound
    6  pip install --upgrade requests regex pytricia expiringdict
    7  apt-get install -y python-pip
    8  pip install --upgrade requests regex pytricia expiringdict
    9  cd /etc/unbound/
   10  ls
   11  wget https://github.com/cbuijs/unbound-dns-firewall/archive/master.zip
   12  apt-get install zip
   13  unzip master.zip
   14  ls
   15  cp -R unbound-dns-firewall-master/* .
   16  ls
   17  ls -al
   18  nano unbound.conf
   19  service unbound stop
   20  unbound -d -c unbound.conf
   21  history

maybe i miss something?

**Comment by w0ngjowo** [comment]
@cbuijs 
finally i try to recompile unbound from source and work,
i think install unbound from apt won`t work because this unbound come with libpython3.5 not with libpython2.7
https://packages.debian.org/stretch/unbound

**Comment by cbuijs** [comment]
@w0ngjowo 

Awesome it works now! Thanks for finding out and sharing the info, I just discovered the same on a freshly installed system (my own system is probably a bit convoluted due all tests etc).

Again thanks for this useful/import piece of info and spending time/effort figuring out. Appreciated!
