### ISSUE TITLE
Reverse IPv6

### ISSUE THREAD

**Issue by rfminelli** [cbuijs/unbound-dns-firewall#31]
How to use only for reverse IPv6?

**Comment by cbuijs** [comment]
@rfminelli 

You mean filter out only reverse IPv6 lookups?

Make sure 'blockv6' is 'false' to not to block out any other IPv6 related queries and then block `ip6.arpa` as domain in a blacklist.

Note: Make sure that it (`ip6.arpa`) is not in a whitelist either as whitelists take precedence over blacklists.

**Comment by rfminelli** [comment]
Actually, I try to find a script that manages the reverse IPv6 when Unbound is queried.

**Comment by cbuijs** [comment]
@rfminelli 

Could you provide an example?

Like an example when doing a query and what the result should be? It is not completely clear to me what you need. The more detail the better :-).

**Comment by rfminelli** [comment]
Today to do the reverse I have to create as inputs to IPv4 and IPv6 (example only of IPv4):
local-zone: "200.200.200.in-addr.arpa." static
               local-data: "200.200.200.in-addr.arpa. 300 IN SOA ns1.yourdomain.com.br. postmaster.yourdomain.com.br. 2017070504 3600 800 86400 30"
               local-data: "1.200.200.200.in-addr.arpa. 300 IN PTR client-200.200.200.yourdomain.com.br."
               local-data: "2.200.200.200.in-addr.arpa. 300 IN PTR client-200.200.200.yourdomain.com.br."
               local-data: "3.200.200.200.in-addr.arpa. 300 IN PTR client-200.200.200.yourdomain.com.br.

and so on until the end of the block.

I would like to find a script that does this automatically in python.
So you would not have to create a one manually.
It would be like Bind's generate.

So when making the reverse query:
dig -x 200.200.200.2
would return:
;; ANSWER SECTION:
2.200.200.200.in-addr.arpa. 300	IN	PTR	client-200.200.200.2.yourdomain.com.br.

I hope I have been able to explain.

**Comment by cbuijs** [comment]
@rfminelli 

Ah. Understand now :-).

Basically you want the `$GENERATE` from bind implemented in UNBOUND. My DNS-Firewall is **not** equipped to do so I am afraid. I abandoned development to put my effort into "[Instigator](https://github.com/cbuijs/instigator)" instead. It is a great feature which I will put on the todo list.

**Comment by cbuijs** [comment]
See #32

**Comment by cbuijs** [comment]
@rfminelli 

I made this into my <a href="https://github.com/cbuijs/instigator">DNS instigator server</a>, you can add an generator aliases (based on regex), like the following examples:

For IPv4:
`/^([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)\.in-addr\.arpa$/=client.\4.\3.\2.\1.yourdomain.com.br`

And for IPv6:
`/^([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.([0-9a-f])\.ip6\.arpa$/=client.\32\31\30\29.\28\27\26\25.\24\23\22\21.\20\19\18\17.\16\15\14\13.\12\11\10\9.\8\7\6\5.\4\3\2\1.yourdomain.com.br`

I will look if I can backport this to DNS-Firewall for Unbound if I can find the time.

**Comment by cbuijs** [comment]
Further communications on this, please use #32
